### ISSUE TITLE
Command to add new network to shared uplink set

### ISSUE THREAD

**Issue by frankzo** [HewlettPackard/POSH-HPEOneView#10]
After the creation of a new network in HP oneview I need to add the network to a uplink set in a logical interconnect group..  
After that I need to update te logical interconnect to reflect the changes in the logical interconnect group. 

I found a command to create a new network; also found al command to update de logical interconnects. 
But how can I add the new network tot a uplink set  on a logical interconnect group.

**Comment by ChrisLynchHP** [comment]
We don't have a native CMDLET to accomplish this yet.

You will need to do the following:

```PowerShell
$LI = "Enclosure-LI"
$UplinkSetName = "UplinkSet1"
$NewNetwork = Get-HPOVNetwork "Name"  #Get the Network resource
$lig = Get-HPOVLogicalInterconnectGroup "LIG NAME" #Get the Logical Interconnect Resource
$lig.uplinkSets | ? { $_.name -eq $UplinkSetName } #Show the existing network URIs from the Uplink Set
($lig.uplinkSets | ? { $_.name -eq $UplinkSetName }).networkUris += $NewNetwork.uri #Add NewNetwork to the networkUris Array
$lig.uplinkSets | ? { $_.name -eq $UplinkSetName } #Show the updated array value
Set-HPOVResource $lig | Wait-HPOVTaskComplete
Update-HPOVLogicalInterconnect $LI
```

**Comment by ChrisLynchHP** [comment]
Closing issue.  If you are still experiencing issues, please re-open or create a new issue to track.

**Comment by frankzo** [comment]
Hi, still using this! Is there any update for an native CMDLET to do this?

**Comment by frippe75** [comment]
+1

**Comment by ChrisLynchHPE** [comment]
So, to help me design Set Cmdlets better, I'd like to know how folks would like to use them.  So, for this type of Cmdlet, there are associations that need to be made.  Like Uplink Ports, and Networks.  I'd like to specifically know, which behavior you'd rather see:

* Provide a list of networks (`-Network` parameter) or ports (`-Ports` parameter) to append to the existing list.
* Provide a list of networks (`-Network` parameter) or ports (`-Ports` parameter) that are the new membership, overwriting the original values.
* Provide a list of New networks (`-NewNetworks` parameter) or New ports (`-NewPorts` parameter), and a list of networks (`-NetworksToRemove` parameter) to remove or ports (`-PortsToRemove` parameter) to remove.

**Comment by frippe75** [comment]
**Discussed with some collegues and:**

I would say that the most intuitive option from my stand point is 

Set-HPOVUplinkset –Network <Networks to be appended > -Port < Uplinkports to be appended > -RemoveNetwork < Networks to be removed from UplinkSet > -RemovePort < Ports to be removed from UplinkSet >

Options like Link Speed and Failover mode would be nice to have as well…

**Comment by ChrisLynchHPE** [comment]
[Set-OVNetworkSet](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.30/networking/set-ovnetworkset) (Legacy Cmdlet Name [Set-HPOVNetworkSet](https://hpe-docs.gitbook.io/posh-hpeoneview/cmdlets/v5.20/networking/set-hpovnetworkset)) was added into the 5.00 and newer libraries.

Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
