### ISSUE TITLE
compare templates

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPEOneView#105]
Please fill in as much information as possible to help resolve your issue.
### Expected Behavior

I would like to be able to get more detailed information regarding inconsistency between templates and server profile attached to that template. It would be also nice to compare two templates and diff between them. Is there any cmdlet for this?

**Comment by ChrisLynchHPE** [comment]
There isn't a Cmdlet available for this yet.  It is on my list of Cmdlets to add.  I do not have an ETA yet.

**Comment by 5truja** [comment]
Thanks Chris.

**Comment by ChrisLynchHPE** [comment]
We are working on adding this Cmdlet to the 2.00 library.

**Comment by 5truja** [comment]
Thanks Chris,


12 juli 2016 kl. 20:30 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


We are working on adding this Cmdlet to the 2.00 library.

-

**Comment by ChrisLynchHPE** [comment]
This functionality was added to core HPE OneView and the library introduced a compliance preview report when using the `Update-OVServerProfile` Cmdlet.

Closing due to no further activity.
