### ISSUE TITLE
Requested bandwidth - auto

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPEOneView#106]
Please fill in as much information as possible to help resolve your issue.
### Expected Behavior

I created server template and my Fibrechannel connections (on Mezzanine) are sucessfully created but I would like to be able to create them without requested bandwidth or actually I would like these to be "Auto" when created. Is this possible?

**Comment by ChrisLynchHPE** [comment]
You do not have to specify Bandwidth in the `New-HPOVServerProfileConnection` Cmdlet.  However, there isn't an `Auto` assignment of bandwidth option, as that isn't available via the API.  However, I could look at implementing a PowerShell specific `Auto` option.

**Comment by 5truja** [comment]
Thanks again.

Kind regards

**Comment by daveolker** [comment]
I was just about to submit this same enhancement request when I found this issue.  I recently created a tool to help C7000 customers migrate their server profiles to Synergy and when extracting the VC server profiles it returns "Auto" for the requested bandwidth value.  I was hoping this same "Auto" value could be used when creating new connections, both Ethernet, FC, FCoE, etc.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
