### ISSUE TITLE
Add a filter function to "Get-HPOVAuditLog"

### ISSUE THREAD

**Issue by 24106934** [HewlettPackard/POSH-HPEOneView#265]
Please fill in as much information as possible to help resolve your issue.

Can a filter function be added to "Get-HPOVAuditLog" ?
The current setup gives me the complete audit dump. This is slow and impacts the appliance.
We would like to add a filter option to only retrieve for example all events of the last 2 hours.
This works for the Rest API

Retrieval and scan on recent audits events is required for us, and would be nice to do this completely in powershell. As Oneview lacks a syslog option, this is a workaround to do this.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.00
HPE OneView Appliance Version:  3.0.1221.2746
Output from `$PSVersionTable` on your Windows Host:

**Comment by ChrisLynchHPE** [comment]
Sure.  I'll take the parameters that `Get-HPOVAlert` provides and incorporate that into the 3.00 library.

**Comment by ChrisLynchHPE** [comment]
I just checked and the functionality you are asking for already exists.  Do you not see -Count, -Timespan, -Start or -End?

Sent from my Windows 10 phone

**Comment by 24106934** [comment]
Just updated to Release 3.0.1293.3770, but the cmd **Get-HPOVAuditLog** does not have these options. 
If i try to use the -Count option i receive this message.
_Get-HPOVAuditLog : A parameter cannot be found that matches parameter name 'Count'._

**Comment by ChrisLynchHPE** [comment]
Apologies.  I was looking at `Get-HPOVAlert`.

**Comment by ChrisLynchHPE** [comment]
I just published an updated library, addressing this issue.  Please update to [Release 3.0.1358.2596 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.0.1358.2596 ).

**Comment by 24106934** [comment]
Thx, done some testing. And verified i used the correct version. 
Used 3.0.1358.2596. And the HPOV  3 - 00 - 3.00.07-0288219 300 HPE OneView VM - VMware vSphere
But _Get-HPOVAuditLog -start ([DateTime]::Now).AddDays(-1)_
Still returns all events... 
Also for -Timespan of days or hours. 
Adding -Count parameter gets the first xx events of my appliance from over 1 year ago. Also tried start and end of specific days ago. 
Could it be that my events use UTC timestamps ? like 2016-11-24 08:55:41.319 UTC

**Comment by ChrisLynchHPE** [comment]
No.  The DateTime object is automatically converted to UTC for the appliance.  I will have to look into this further, as I am not sure what is happening here.

**Comment by ChrisLynchHPE** [comment]
Closing due to further inactivity.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
