### ISSUE TITLE
rules for contributing or improving scripts?

### ISSUE THREAD

**Issue by mi-hol** [HewlettPackard/POSH-HPEOneView#310]
I miss a description for handling community contributions.
maybe its just an oversight or worst case it may not be desired.
Please clarify.

Example from https://github.com/PowerShell/PowerShell/tree/v6.0.1: 
'Developing and Contributing
Please see the Contribution Guide for how to develop and contribute.'

**Comment by ChrisLynchHPE** [comment]
It is an oversight.  I haven't published the details on how the community can contribute to the project.  As it stands right now, you can fork the repo here, work on one or more fixes, and then generate a Pull Request.  The requirement here will be that the Pull Request must be for the original Branch.  Each branch is a specific `Major.Minor` release, and does not get merged back into another Branch, including `master`.

If you want to generate a test Pull Request, feel free.  I can always reject the request or merge if needed.

**Comment by mi-hol** [comment]
Thanks Chris.

Regarding "Each branch is a specific Major.Minor release, and does not get merged back into another Branch, including master." I see some issues :(

I've version 3.1 installed and downloaded [https://github.com/HewlettPackard/POSH-HPOneView/blob/3.10/Samples/AddServers_Monitored_Sample.ps1](url)

The script failed initially, because it has a hardcoded reference for the previous version 3.0
'Import-Module HPOneView.300'

Is there a better solution?

**Comment by ChrisLynchHPE** [comment]
They are just samples. Unless there are major changes in the Cmdlets they call, I don't always have the time to update the call to import the current library. They aren't meant to be strictly executed without the user modifying them to suit their infrastructure.

**Comment by mi-hol** [comment]
What I learned over time is that people get quickly frustated when they encounter hurdles along their way to learn new things.
A sample script that throws an error on first use is perceived as a major hurdle by most people!
While I understand your comment 'aren't **meant** to be strictly executed without the user modifying them' there is actually no such comment in the AddServer sample I looked at first.

As the hurdle is caused by the code below, I wonder if it can be removed?
Via the shortcut 'HPE OneView <version> PowerShell Library' created during installation this code shouldn't be executed at all.
code:
if (-not (get-module HPOneview.300)) 
{
    Import-Module HPOneView.300
}

**Comment by ChrisLynchHPE** [comment]
Samples will remain with the library as guidance on how to do more things that Get-Help of a Cmdlet will not display.  They need to be customized for the uses environment.  I have made sure they are updated in the 4.00 and 3.10 libraries, and updates will go out this weekend.

**Comment by mi-hol** [comment]
Thanks, I've seen the updates appear in 4.00. Guess the 3.10 is work-in-progress, right?

**Comment by ChrisLynchHPE** [comment]
Yes.

**Comment by ChrisLynchHPE** [comment]
This was addressed in the [Release 3.10.1588.1229 ](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1588.1229 ) and commit.

Closing.

**Comment by mi-hol** [comment]
@ChrisLynchHPE the issue was solved partially. 
Please reopen to address the original topic 'add in README.md something to explain the rules for 'Developing and Contributing'' 
i.e your comment 'how the community can contribute to the project. As it stands right now, you can fork the repo here, work on one or more fixes, and then generate a Pull Request. The requirement here will be that the Pull Request must be for the original Branch. Each branch is a specific Major.Minor release, and does not get merged back into another Branch, including master.' should be visible there otherwise they are lost.

**Comment by ChrisLynchHPE** [comment]
Sorry. I had mistakenly closed it for the samples update. Yes, I still need to publish contribution statement.

**Comment by ChrisLynchHPE** [comment]
I have been planning on adding a contributing statement to this project for a while. I have to still update dev and build tools, along with unit test framework updates. It is taking longer than expected. But I do hope to have this all resolved in the next month.

**Comment by ChrisLynchHPE** [comment]
I recently published a contribution guide to the [Readme](https://github.com/HewlettPackard/POSH-HPOneView/blob/4.10/README.md) in the project repo.  It is a start, as I have been working through challenges of including the main Pester test script within the repo.  Please take a look.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
