### ISSUE TITLE
Issue with Get-HPOVAuditLog (Filter not used)

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/POSH-HPEOneView#351]
In Get-HPOVAuditLog the $filter is added to the uri if ($Query.count -gt 0).

$Query is not used in the function. (issue in 4.0 and 4.1 Library)

Furthermore filtering on Audit Logs seems only working for a whole day. We cannot get Audit Logs for the past hour for example.

### Expected Behavior
```PowerShell
if ($Filter.count -gt 0)
{
	$uri = '{0}&filter="{1}"' -f $uri, [String]::Join(' and ',$Filter.ToArray())
}
```

### Actual Behavior
No filtering applied due to ($Query -gt 0)
Filtering on past hour not working

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
Sorry to get back so late as I have been doing more research on this.  The API the Cmdlet uses does not offer hour or minute granularity.  I'll be looking at fixing this with PowerShell mechanisms to filter for specific, more granular date and time.
