### ISSUE TITLE
invoke-hpovvcmmigrate

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPEOneView#361]
### Expected Behavior

Report generated when using the -report option

### Actual Behavior

HPOneview.410\Invoke-HPOVVcmMigration -LicensingIntent OneView -OAIPAddress ****** -OAPassword ***** -OAUserName ***** -Report -VCMPassword ******* -VCMUserName ******** -EnclosureGroup ********* -LogicalInterconnectGroup ******* -WhatIf
cmdlet Invoke-HPOVVcmMigration at command pipeline position 1
Supply values for the following parameters:
WARNING: OAPassword paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: OAUsername paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: VCMPassword paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
WARNING: VCMUsername paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPOneview.410\HPOneView.410.psm1:39100 char:4
+             $_VCEMPassword = $VCEMPassword.clone()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
HPOneview.410\Invoke-HPOVVcmMigration : The field named logicalInterconnectGroupName near line 1, column 382 is not a valid field in this JSON object. Check the valid fields for this JSON 
object and remove or correct the unrecognized field. 
At line:1 char:1
+ HPOneview.410\Invoke-HPOVVcmMigration -LicensingIntent OneView -OAIPAddress ****. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Invoke-HPOVVcmMigration], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Invoke-HPOVVcmMigration

### Steps to reproduce

connect to appliance and run above command 

###

Understand in latest version that PS credentials are used as others depreciated, can examples be updated on wiki as wiki using old method.

**Comment by jzl2w8** [comment]
Hi - do you have any update or comment on this issue?

**Comment by jpaddock1** [comment]
Retried with the Release 4.10.1802.1882 powershell cmdlets and received the attached errors
[InvokeHPOVVCMScreenShots.docx](https://github.com/HewlettPackard/POSH-HPOneView/files/2370194/InvokeHPOVVCMScreenShots.docx)

with this release i did managed to progress a bit further and create a report as noted in the screen shots. As seen i tried multiple ways even the wiki syntax "Invoke-HPOVVcmMigration [-OAIPAddress] <String> [-OAUserName] <String> [-OAPassword] <String> [-VCMUserName] <String> [-VCMPassword] <String> [-LicensingIntent] <String> [-EnclosureGroup] <Object> [-LogicalInterconnectGroup] <Object>[ [-Async] <SwitchParameter>] [-ApplianceConnection] <Object>[ [-WhatIf] <SwitchParameter>][ [-Confirm] <SwitchParameter>] [<CommonParameters>]"

**Comment by jpaddock1** [comment]
Thanks Chris for the update. I provided a new pscredential as a variable which resolved part of what i saw before. 
if i run the command as

Invoke-HPOVVcmMigration -LicensingIntent OneView -OACredential $oaadmin -OAIPAddress xxx.xxx.xxx.xxx -OAPassword ****** -OAUserName ******** -Report -VCMCredential $vcadmin -VCMPassword ****** -VCMUserName ******  -Path f:\jeff -WhatIf   #-EnclosureGroup ********** -LogicalInterconnectGroup ********

i receive 

WARNING: OAPassword paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: OAUsername paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: VCMPassword paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
WARNING: VCMUsername paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\HPOneView.410.psm1:39955 char:5
+                 $_VCEMPassword = $VCEMPassword.clone()
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
What if: Performing the operation "Output to File" on target "f:\jeff\***********.report".
Report saved to: f:\jeff\********.report
Invoke-HPOVVcmMigration : There are 1 or more critical issues preventing the enclosure from being eligible to migrate.

 (The critical error i reviewed and understand what needs to be corrected)

but if i try and run the command with the enclosure and logicalinterconnect options i receive 

WARNING: OAPassword paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: OAUsername paramter is being deprecated.  Please upsate and use the -OACredential parameter.
WARNING: VCMPassword paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
WARNING: VCMUsername paramter is being deprecated.  Please upsate and use the -VCMCredential parameter.
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\HPOneView.410.psm1:39955 char:5
+                 $_VCEMPassword = $VCEMPassword.clone()
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Invoke-HPOVVcmMigration : The field named logicalInterconnectGroupName near line 1, column 382 is not a valid field in this JSON object. Check the valid fields for 
this JSON object and remove or correct the unrecognized field. 
At line:4 char:1
+ Invoke-HPOVVcmMigration -LicensingIntent OneView -OACredential $oaadmin -OAIPAdd ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Invoke-HPOVVcmMigration], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Invoke-HPOVVcmMigration


also if i omit the -oausername/password and vcusername/password from the command i still get prompted to enter them

Supply values for the following parameters:
OAUserName: 
OAPassword: 
VCMUserName: 
VCMPassword: 

could you kindly confirm if the syntax of the command being used is correct, thank you for all your  assistance.

**Comment by ChrisLynchHPE** [comment]
Please use the `Get-HPOVCommandTrace` to capture the output and provide the created file.  I'll need to look at this with more detail.

**Comment by jpaddock1** [comment]
[Ivoke-vcmigrate_report.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/2374496/Ivoke-vcmigrate_report.txt)
output from the trace command attached

**Comment by ChrisLynchHPE** [comment]
You need to omit the `-LogicalInterconnectGroup` parameter.  That is only needed if you want to specify a custom LIG name when the Enclosure Group doesn't exist and a Logical Interconnect Group needs to be created.

**Comment by jpaddock1** [comment]
Hi Chris,
i created a simple script to test for the migration which can be controlled via csv file so nothing needed to be hard coded as below

$testmig = Import-Csv G:\OneView\OneViewAppliance-master\Variables\EnclosureMigration.csv

foreach($item in $testmig) 
     {
       Write-host $item

       $vcadmin = New-Object System.Management.Automation.PSCredential ($item.VCMUserName, (ConvertTo-SecureString $item.VCMPassword -AsPlainText -Force))
       $oaadmin = New-Object System.Management.Automation.PSCredential ($item.OAUserName, (ConvertTo-SecureString $item.OAPassword -AsPlainText -Force))

       if ($item.Report -eq "Yes")

          {
          Write-host "You chose to generate a report, once validated, change to NO to import enclosure"

          Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACredential $oaadmin -OAIPAddress $item.OAIPAddress  -Report -VCMCredential $vcadmin  -Path $item.path  -EnclosureGroup $item.Enclosuregroup  -OAUserName $item.OAUserName  -OAPassword $item.OAPassword   -VCMPassword $item.VCMPassword -VCMUserName $item.VCMUserName

          }
       
        if ($item.Report -eq "No")

          {
          Write-host "You chose to generate a report, once validated, change to NO to import enclosure"

          Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACredential $oaadmin -OAIPAddress $item.OAIPAddress -OAPassword $item.OAPassword -OAUserName $item.OAUserName  -VCMCredential $vcadmin -VCMPassword $item.VCMPassword -VCMUserName $item.VCMUserName  -Path $item.path  -EnclosureGroup $item.Enclosuregroup

          }
       
       
       else
           {

           Write-host "No correct Yes or No option defined in the reporting variable - exiting"
           return

           }


     }

however, if i use this method, it fails with the below msg

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\HPOneView.410.psm1:39955 char:5
+                 $_VCEMPassword = $VCEMPassword.clone()
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Invoke-HPOVVcmMigration : The Onboard Administrator at *********, cannot be contacted with the provided credentials.
At line:15 char:11
+           Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACred ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Invoke-HPOVVcMigration:String) [Invoke-HPOVVcmMigration], EnclosureResourceException
    + FullyQualifiedErrorId : FAIL_BAD_CREDENTIALS_FOR_OA,Invoke-HPOVVcmMigration
 



if i omit these from the script line by doing # -OAUserName $item.OAUserName  -OAPassword $item.OAPassword   -VCMPassword $item.VCMPassword -VCMUserName $item.VCMUserName


 the invoke prompts me to enter for the OA and VC credentials and still fails to run.



So far the command will run if i type all details for the OA and VC usernames and passwords rather than having these defined as variable inputs

**Comment by ChrisLynchHPE** [comment]
When I added `PSCredential` support to this Cmdlet, I missed setting the original parameters to optional.  I have fixed this in the 4.10 update I'm publishing today.

**Comment by jpaddock1** [comment]
thank you, will give a try

**Comment by jpaddock1** [comment]
ModuleType Version        Name          ExportedCommands                                                                                    
---------- -------        ----          ----------------                                                                                    
Script     4.10.1821.1567 HPOneView.410 {Add-HPOVApplianceTrustedCertificate, Add-HPOVBaseline, Add-HPOVEnclosure, Add-HPOVFabricManager...}

when omitting the option OA and VC i still received the prompt

cmdlet Invoke-HPOVVcmMigration at command pipeline position 1
Supply values for the following parameters:
OAUserName: 

cmd line used as:

Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACredential $oaadmin -OAIPAddress $item.OAIPAddress  -Report -VCMCredential $vcadmin  -Path $item.path  -EnclosureGroup $item.Enclosuregroup  

Variables removed from original line -OAUserName $item.OAUserName  -OAPassword $item.OAPassword   -VCMPassword $item.VCMPassword -VCMUserName $item.VCMUserName

**Comment by ChrisLynchHPE** [comment]
The update hasn't been published yet.  You are seeing the behavior I recently noted above.  I'm working through some of the test gate failures with the library (which is all with the test environment, not the modules).

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 4.10.1821.1567](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v4.10.1821.1567) and in [PowerShell Gallery](https://www.powershellgallery.com/packages/HPOneView.410/4.10.1821.1567).

Please verify before this issue is closed.

**Comment by jpaddock1** [comment]
I receive the same input request for OA VC


PS C:\Windows\system32> Get-Module -Name HPOneView.410 | Format-Table -AutoSize

ModuleType Version        Name          ExportedCommands                                                                                    
---------- -------        ----          ----------------                                                                                    
Script     4.10.1821.1567 HPOneView.410 {Add-HPOVApplianceTrustedCertificate, Add-HPOVBaseline, Add-HPOVEnclosure, Add-HPOVFabricManager...}



PS C:\Windows\system32> $testmig = Import-Csv D:\_jeff\EnclosureMigration.csv

foreach($item in $testmig) 
     {
       Write-host $item
       
       $vcadmin = New-Object System.Management.Automation.PSCredential ($item.OACredential, (ConvertTo-SecureString $item.VCMPassword -AsPlainText -Force))
       $oaadmin = New-Object System.Management.Automation.PSCredential ($item.VCMCredential, (ConvertTo-SecureString $item.OAPassword -AsPlainText -Force))

       if ($item.Report -eq "Yes")

          {
          Write-host "You chose to generate a report, once validated, change to NO to import enclosure"

          Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACredential $oaadmin -OAIPAddress $item.OAIPAddress  -Report -VCMCredential $vcadmin  -Path $item.path  -EnclosureGroup $item.Enclosuregroup 

          }
       
        if ($item.Report -eq "No")

          {
          Write-host "You chose to generate a report, once validated, change to NO to import enclosure"

          Invoke-HPOVVcmMigration -LicensingIntent $item.LicensingIntent -OACredential $oaadmin -OAIPAddress $item.OAIPAddress  -VCMCredential $vcadmin -path $item.path  -EnclosureGroup $item.Enclosuregroup

          }
       
       
       else
           {

           Write-host "No correct Yes or No option defined in the reporting variable - exiting"
           return

           }


     }
@{LicensingIntent=OneView; OACredential=******; OAPassword=****; OAIPAddress=****** ; VCMCredential=*******; VCMPassword=*****; En
closuregroup=*******; report=Yes; path=d:\_jeff }
You chose to generate a report, once validated, change to NO to import enclosure
cmdlet Invoke-HPOVVcmMigration at command pipeline position 1
Supply values for the following parameters:
OAUserName:

**Comment by jpaddock1** [comment]
OK thanks, will wait for the updated version to be published

**Comment by jpaddock1** [comment]
Hi Chris, has the updated version being released

**Comment by jpaddock1** [comment]
Hi Chris, has the updated version being released

**Comment by ChrisLynchHPE** [comment]
Not yet.  I'm working on a few other items, but will be released in the next week.

**Comment by jpaddock1** [comment]
Hi Chris, any further update on this pls?

**Comment by jpaddock1** [comment]
Hi Chris, any further update on this pls?

**Comment by ChrisLynchHPE** [comment]
Yes, I am still working on an update to the 4.10 library.

**Comment by jpaddock1** [comment]
Thanks for the update, is there any ETA that i can feed back into my project pls.(Apologies if it may seem like a chaser)

**Comment by ChrisLynchHPE** [comment]
The earliest could be Nov 2nd.

**Comment by jpaddock1** [comment]
Hi Chris, any update, thank you in advance

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
