### ISSUE TITLE
Install-HPOVLogicalInterConnectFirmware

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPEOneView#367]
Issue in defining -baseline for the above command. Attached log for reference.

I did note  that the example uses Get-HPOVSppFile but log refers to Get-HPOVBasline
[Install-HPOVLICFW-OutputError.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/2428086/Install-HPOVLICFW-OutputError.txt)

**Comment by ChrisLynchHPE** [comment]
Please use the following instead:

```PowerShell
$Baseline = Get-HPOVBaseline -Name "Service Pack for Proliant" -ErrorAction Stop
Install-HPOVLogicalInterconnectFirmware -Baseline $Baseline -Method Stage
```

**Comment by jpaddock1** [comment]
Thank you for the resolution to baseline, this has now being corrected but still error on appliance connection requirement

PS C:\Windows\system32> Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect $LIG  -Method Stage  -WhatIf
WARNING: Module activation may cause a network outage if Activation Order is Parallel.
What if: Performing the operation "update and activate Interconnect modules" on target "*********".
Install-HPOVLogicalInterconnectFirmware : Cannot validate argument on parameter 'ApplianceConnection'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
At line:1 char:1
+ Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-HPOVLogicalInterconnectFirmware], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Install-HPOVLogicalInterconnectFirmware

PS C:\Windows\system32> Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect $LIG  -Method Stage -ApplianceConnection $ConnectedSessions.name -WhatIf
WARNING: Module activation may cause a network outage if Activation Order is Parallel.
What if: Performing the operation "update and activate Interconnect modules" on target "************".
Install-HPOVLogicalInterconnectFirmware : Cannot validate argument on parameter 'ApplianceConnection'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
At line:1 char:1
+ Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-HPOVLogicalInterconnectFirmware], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Install-HPOVLogicalInterconnectFirmware
 

And if i manually enter the address

PS C:\Windows\system32> Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect $LIG  -Method Stage -ApplianceConnection xxx.xxx.xxx.xxx -WhatIf
WARNING: Module activation may cause a network outage if Activation Order is Parallel.
What if: Performing the operation "update and activate Interconnect modules" on target "**************".
Install-HPOVLogicalInterconnectFirmware : Cannot validate argument on parameter 'ApplianceConnection'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
At line:1 char:1
+ Install-HPOVLogicalInterconnectFirmware -Baseline $baseline -LogicalInterconnect ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Install-HPOVLogicalInterconnectFirmware], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Install-HPOVLogicalInterconnectFirmware
 

PS C:\Windows\system32> Get-Module -nam HPOneView.410 | Format-Table -AutoSize

ModuleType Version        Name          ExportedCommands                                                                                    
---------- -------        ----          ----------------                                                                                    
Script     4.10.1821.1567 HPOneView.410 {Add-HPOVApplianceTrustedCertificate, Add-HPOVBaseline, Add-HPOVEnclosure, Add-HPOVFabricManager...}

**Comment by jpaddock1** [comment]
Hi Chris, any update, thank you in advance

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
