### ISSUE TITLE
Error creating Profile specifying both Template and Settings

### ISSUE THREAD

**Issue by davew1234** [HewlettPackard/POSH-HPEOneView#373]
### Expected Behavior
Cannot create a new profile specifying both a template and also other settings at the same time. Only works with template only, or no template and all settings. I also don't see a method to edit a profile or template to add settings once it has been created.

### Actual Behavior
  Works:
```PowerShell
  $Task = New-HPOVServerProfile -ServerProfileTemplate $ProfileTemplate -Name "$ProfileName" -Description "$ProfileDescription" -AssignmentType "Server" -Server $ProfileBlade
```
  Does not work:
```PowerShell
  $Task = New-HPOVServerProfile -ServerProfileTemplate $ProfileTemplate -Name "$ProfileName" -Description "$ProfileDescription" -AssignmentType "Server" -Server $ProfileBlade -Affinity "Bay"
```
Note: Added -Affinity just as a simple example of the error. All other profile settings are needed too. In particular to add storage and networking.

  Error:
```PowerShell
  PS>TerminatingError(New-HPOVServerProfile): "Parameter set cannot be resolved using the specified named parameters."
  New-HPOVServerProfile : Parameter set cannot be resolved using the specified named parameters.
  At C:\Data\SFL Lab\HPE\Common-HPE.ps1:765 char:9
  + $Task = New-HPOVServerProfile -ServerProfileTemplate $ProfileTemplate ...
  +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : InvalidArgument: (:) [New-HPOVServerProfile], ParameterBindingException
      + FullyQualifiedErrorId : AmbiguousParameterSet,New-HPOVServerProfile
```
### Steps to reproduce
Examples given above. It looks like a problem with parsing the parameters. I noticed there is a `-Server` parameter as well as several `-ServerXxxxx` parameters. I'm wondering if this creates an ambiguous situation. Maybe `-Server` should be `-ServerDevice`. This looks like a PowerShell error.

### Version Information
PowerShell: 5.1.14409.1012
HPOneView.410: 4.10.1821.1567
OneView (Synergy): 4.10.03.364293.00

**Comment by ChrisLynchHPE** [comment]
I'll have to take a look at this further.  Do know that modifying Volumes and Networking in the SP when creating from an SPT will cause a compliance issue.  Is that your intent?  What is the reason you need to change the server profile settings when creating from a template?

**Comment by ChrisLynchHPE** [comment]
BTW, your example on trying to use `-Affinity` is not correct.  Please refer to the syntax help for `New-HPOVServerProfile`.

**Comment by davew1234** [comment]
Hi Chris. Thanks for looking into this. This is our primary use for automation with OneView, to manage profiles and profile templates. So there will be a lot of various settings and reasons for the parameters. My validation for script design is to ensure it works in OneView, then automate that. I am able to create a profile with a template and additional settings using OneView (in fact I can overwrite settings in the template during creation with OneView, albeit with compliance alert), but consistently received the error when doing this with the POSH API.

I am not seeing the issue with the -Affinity parameter usage, but that's not important for now to resolve, I don't think, since I get the same error with all other profile settings.

Background:
Originally I was going to put all settings in an SPT, then deploy a profile with minimal additional settings. That works fine and I can make all the settings in a template and deploy to a profile with just a template reference.

From actual use, I found that there are some settings that will almost always be different for each server (profile), such as disk allocations and networking. In some cases allowing firmware updates. This is due to different application requirements and department policies (server owner). When this happens the profile is flagged as yellow and out of compliance. We would end up with a large number of profiles always out of compliance and thus the usage of compliance would be ignored by operations.

My  current strategy is to put in an SPT only what can be enforced operationally, then put most settings in the profile. Templates are a compliance enforcement tool only (for our strategy). Since the profile is being created with a script, the script ensures profile compliance and IT standards, the template ensures future compliance as appropriate. Then provide processes and automation for operations to enforce compliance with templates in the future.

Thus I need to create a server profile with a reference to a template and make additional settings, which by the way, do not exist in the template. The programming rule here is a profile creation will never make settings that are in the template. This is enforced via the script engineering, since the script automation sets will create all templates and deploy all profiles. What is provided in a template varies per application and department.

I had considered not using templates, but I would like to use them even if no settings, to be consistent in usage. This seems like a good compliance feature in OneView that I would like to keep in the environment and see how to use more in the future.

Sorry I didn't have more background in the original ticket. I'm sure it helps for you to understand end user use cases. Let me know if you have questions, or thoughts, or I missed something.

Regards,
Dave

**Comment by ChrisLynchHPE** [comment]
Unfortunately, what you stated above is not how server profile to template associations work.  SPT's declare the desired policy, and the server profile(s) created from it will then deploy that configuration.  You cannot selectively deploy parts of the server profile from the server profile template without disassociating the server profile from the server profile template.  That would then of course make it difficult to change en-masse multiple, common settings without modifying all server profiles.

**Comment by ChrisLynchHPE** [comment]
And that being said, there are a few parameters that should be allowed in the Cmdlet, which are missing a needed parameter set declaration.  I'll address those in the next 4.10 library update.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
