### ISSUE TITLE
Unable to change user Idle-Timeout time

### ISSUE THREAD

**Issue by jpaddock1** [HewlettPackard/POSH-HPEOneView#376]
ApplianceVersion: 4.10

both GET on /rest/sessions & /rest/sessions/idle-timeout fail with bad request

**Errors**
Invoke-RestMethod -Method get -Uri $url/rest/sessions -Headers $headers   -Verbose

VERBOSE: GET https://********/rest/sessions with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At line:19 char:1
+ Invoke-RestMethod -Method get -Uri $url/rest/sessions -Headers $headers   -Verbo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 

Invoke-RestMethod -Method get -Uri $url/rest/sessions/idle-timeout -Headers $headers   -Verbose

VERBOSE: GET https://*********/rest/sessions/idle-timeout with 0-byte payload
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At line:19 char:1
+ Invoke-RestMethod -Method get -Uri $url/rest/sessions/idle-timeout -Headers $hea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Expected Results**

GET https://{appl}/rest/sessions/idle-timeout
  
Session-Id: abcdefghijklmnopqrstuvwxyz012345
X-Api-Version: 800
                    
Response

HTTP/1.1 200 OK
Content-Type: application/json

{
    "idleTimeout":86400000
}

GET https://{appl}/rest/sessions

Session-Id: abcdefghijklmnopqrstuvwxyz012345
Session-Keepalive:true
X-Api-Version: 800
  
                        
Response

HTTP/1.1 200 OK
Content-Type: application/json

{
    "clientHost":"example.net",
    "loggingID":"abcdefg",
    "loginDomain":"Local",
    "permissions":[
        {
            "roleName": "Infrastructure administrator",
            "scopeUri": "/rest/scopes/8a500585-4289-49b1-a7e9-687a727504bf",
            "active": true
        },
        {
            "roleName": "Infrastructure administrator",
            "scopeUri": "/rest/scopes/dbac53eb-feae-42ec-969a-6cc504457980",
            "active": true
        },
        {
            "roleName": "Infrastructure administrator",
            "scopeUri": null,
            "active": true
        }
    ],
    "serverHost":"example.net",
    "sessionID":"abcdefghijklmnopqrstuvwxyz012345",
    "userDefinedData":"",
    "username":"administrator"
}

**Comment by ChrisLynchHPE** [comment]
Why are you using `Invoke-RestMethod` and not `Send-HPOVRequest`?

**Comment by jpaddock1** [comment]
didnt quite get it working either

PS C:\Windows\system32> Send-HPOVRequest -uri /rest/appliance/device-read-community-string

communityString                                         uri                                                    ApplianceConnection                                   
---------------                                         ---                                                    -------------------                                   
*****_read                                            /rest/appliance/device-read-community-string           xxx.xxx.xxx.xxx                                       

The above used to testing that connection was OK

PS C:\Windows\system32> Send-HPOVRequest -uri /rest/sessions/idle-timeout
Send-HPOVRequest : Missing mandatory header Session-ID from the request. Please provide the missing parameter. 
At line:1 char:1
+ Send-HPOVRequest -uri /rest/sessions/idle-timeout
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Send-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest
 

PS C:\Windows\system32> Send-HPOVRequest -uri /rest/sessions/idle-timeout -AddHeader $ConnectedSessions[0].SessionID
Send-HPOVRequest : Cannot process argument transformation on parameter 'AddHeader'. Cannot convert the "NTcwODAyODU4ODMwt4ffqK-5Wkx4t6W8MH4eCcFFC_OxQUMx" value of 
type "System.String" to type "System.Collections.Hashtable".
At line:1 char:62
+ Send-HPOVRequest -uri /rest/sessions/idle-timeout -AddHeader $ConnectedSessions[ ...
+                                                              ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-HPOVRequest], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Send-HPOVRequest

**Comment by ChrisLynchHPE** [comment]
You need to establish a valid session to the appliance, then you can use `Send-HPOVRequest` to public URI's that are available.

Now, you are trying to get some information from the appliance.  [Show-HPOVActiveUser](https://github.com/HewlettPackard/POSH-HPOneView/wiki/Show-HPOVActiveUser) will return you the logged in user accounts.

The second error looks to be an API issue, not with either using` Invoke-RestMethod` or `Send-HPOVRequest`.

**Comment by ChrisLynchHPE** [comment]
And what is it you are trying to accomplish?

**Comment by jpaddock1** [comment]
looking to change the idle time to say 15 mins if local user accounts are logged in.

**Comment by ChrisLynchHPE** [comment]
Trying to change the idle session timeout would only be for your user account, not for all users.  And this would never impact the UI, unless the user closed out of their web browser and then returned to their browser accessing the appliance after the timeout has lapsed.

This is a bug with OneView, not the library.  There isn't much more I can do here.

**Comment by peter-wolfe** [comment]
You need pass in a valid session id as part of the header for this specific REST request (e.g. use your current auth token). However, as Chris noted, if there is as active browser window for the user, the browser activity would act as a keepalive and the session would never be considered idle

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
