### ISSUE TITLE
Set-HPOVNetworkSet Replaces networks. How do I add

### ISSUE THREAD

**Issue by NJBean** [HewlettPackard/POSH-HPEOneView#394]
When I use the Set-HPOVNetworkSet command, I can not find a good way to add new networks. I can get the networks uri from an exsisting network but I can’t find a way to get exsisting and add new networks with the way get-hpovnetworkset outputs data. When I try to run set-hpovnetworkset with just new networks defined it over writes the exsisting config.

**Comment by ChrisLynchHPE** [comment]
I'll look at adding some new parameters, like `-RemoveNetwork' and '-AddNetwork' to the Cmdlet in a future relese.

**Comment by ChrisLynchHPE** [comment]
I have added this functionality to the just released HPE OneView 4.20 library.  I am working on back porting it to the 4.10 library as well.

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
