### ISSUE TITLE
Get-HPOVServerProfile module with detailed giving Boot order output 

### ISSUE THREAD

**Issue by ajayvaaka** [HewlettPackard/POSH-HPEOneView#404]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior

$x =Get-HPOVServerProfile -name test -Detailed

no output displayed expected

## Actual Behavior

$x =Get-HPOVServerProfile -name test -Detailed

This module is providing info it needed but throwing output with **Boot order** . 
Boot Order
----------
* I tried with out-null , still no luck 

### Steps to reproduce

```PowerShell
# 1. Capture verbose output using the Get-HPOVCommandTrace for HPOneView.310 or newer, or append the -Verbose switch to your Cmdlet call.
# 2. Put your code and/or captured output here.
# 3. Remove this comment block before submitting.
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`):
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  
Output from `$PSVersionTable` on your Windows Host:

```PowerShell
# Output from $PSVersionTable
```

**Comment by ChrisLynchHPE** [comment]
Can you please provide the output from `$PSLibraryVersion`?

**Comment by ajayvaaka** [comment]
@ChrisLynchHPE 

Name  : PSVersion
Value : 5.1.14409.1012

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.14409.1012

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

HPE installed module .
4.10.20... HPOneView.410

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you wish, feel free to re-open to discuss further.
