### ISSUE TITLE
New-HPOVServerProfile does not accept SnAssignment flag with ServerProfileTemplate 

### ISSUE THREAD

**Issue by jdkarpin** [HewlettPackard/POSH-HPEOneView#413]
Hi,
When you try to create ServerProfile with -ServerProfileTemplate flag, there's no way to choose different MacAssignment, WwnAssignment, SnAssignment than Virtual (it's default).

### Expected Behavior
Serial Number can be Virtual "Virtual", "Physical", "UserDefined" in ParameterSetName SPT.

### Actual Behavior
Flags SnAssignment, WwnAssignment, MacAssignment cannot be used with SPT ParameterSetName. 

### Steps to reproduce
It's just command definition. 

```PowerShell
		[Parameter (Mandatory, ParameterSetName = "SPT")]
		[Object]$ServerProfileTemplate,
(...)
		[Parameter (Mandatory = $false, ParameterSetName = "Default")]
		[Parameter (Mandatory = $false, ParameterSetName = "SANStorageAttach")]
		[ValidateSet ("Virtual", "Physical", "UserDefined", IgnoreCase)]
		[string]$SnAssignment = "Virtual",
```
```Powershell
PS C:\Users\ad_jdkarpin> $ret = New-HPOVServerProfile -Name hostname -ServerProfileTemplate $template -Server $server -Confirm:$false -AssignmentType Server -Enclosure $enclosure -EnclosureBay 6
PS C:\Users\ad_jdkarpin> $ret.taskErrors

errorCode          : POOL_DISABLED
message            : Unable to perform requested operation on Virtual Serial Number range while the pool is disabled.
details            :
recommendedActions : {Enable the Virtual Serial Number pool and try the request again.}
errorSource        :
nestedErrors       : {}
data               :
```

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion` or `$PSLibraryVersion`): 4.20.2133.3186
HPE OneView Appliance Version (`Get-HPOVVersion -ApplianceVer`):  4.20.02.395878.00
Output from `$PSVersionTable` on your Windows Host: 

```PowerShell
PS C:\Users\ad_jdkarpin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
Why didn't you set this within your profile template?  This isn't a bug, just not implemented.

**Comment by jdkarpin** [comment]
Hi,
In template it's not set, but in HPE OneView GUI by default it's set to physical, when profile is being created.

Regarding `-PassThru` - that's what I did as workaround, but in my opinion those 3 flags should be available, or default should be same as in GUI.

Regards,
Jakub

**Comment by ChrisLynchHPE** [comment]
The reason it is default in the UI is because you disabled the ID pools.  And based on behavior here, it appears that the server profile template was created before the ID pools were disabled.  Since you cannot change the ID assignment type after creating the resource, it would be likely difficult to create a new profile template with the right identifier policy, and adjust your server profiles to this new template.

I'll add this to the library backlog as an enhancement.

**Comment by ChrisLynchHPE** [comment]
This feature was added in prior releases of the 5.00 and newer libraries.  Here is the list of currently released libraries:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

**Comment by ChrisLynchHPE** [comment]
Closing due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
