### ISSUE TITLE
Correct/easiest way of determining whether an appliance is OneView for Synergy or Virtual Appliance

### ISSUE THREAD

**Issue by erikgraa** [HewlettPackard/POSH-HPEOneView#527]
Right now I am checking by try-catching-{} Get-OVComposerNode, but perhaps there is an easier way of distinguishing a OneView Virtual Appliance from OneView for Synergy?

**Comment by VincentBerger** [comment]
You can do a GET on /rest/appliance/nodeinfo/version. Specifically look at the modelNumber property
I don't think there is a native cmdlet for it, but you can always use Send-OVRequest

**Comment by erikgraa** [comment]
> You can do a GET on /rest/appliance/nodeinfo/version. Specifically look at the modelNumber property
> I don't think there is a native cmdlet for it, but you can always use Send-OVRequest

Thank you for the suggestion. The ModelName property has exactly what I need.

**Comment by ChrisLynchHPE** [comment]
The easiest way is to look at the `$ConnectedSessions` object created for you.  This already populates a property called `ApplianceType` which derives from the `ModelName` property of the URI call Vincent mentioned.

**Comment by erikgraa** [comment]
Seems I forgot about that one. Thank you for taking the time to clarify.
